### PR TITLE
feature/extend-adjust-integration - added Deeplink integration option

### PR DESCRIPTION
**Pull request by ArkadiGiniApps**

### CODE REVIEW

**Review by samdozor — COMMENTED** [review]
@ArkadiGiniApps thank you for the PR. Do you think it would be appropriate to use the mParticle attribution listener API and just send the callback into there?

**Comment by ArkadiGiniApps** [comment]
not really the mParticle listener is an information only tool. Adjust has the option of responding to deepening event by opening their UI elements (the callback returns a boolean for that use case exactly)

**Comment by samdozor** [comment]
@ArkadiGiniApps are you familiar with our deep-linking/attribution API? you may only use mParticle to log events - it provides you with a single abstraction to respond to deep links from all kits, including adjust. It would be simple to add support for it here. 

You would just do this in the kit: `config.setOnDeeplinkResponseListener(this);` and then implement the response to the deep link just as it's already being done for the attribution listener here: https://github.com/mparticle-integrations/mparticle-android-integration-adjust/blob/master/src/main/java/com/mparticle/kits/AdjustKit.java#L81-L99

Then you'd be able to follow these docs: https://docs.mparticle.com/developers/sdk/android/kits/#deep-linking

**Comment by ArkadiGiniApps** [comment]
@samdozor you're missing the point.

The current implementation of AdjustKit does not allow me to hook into the Adjust configuration object, in the way i need. This is why i opened the PR, to allow for a way of connecting to the needed Adjust listener.

As you are aware in your documentation you specify that for some things the user of mParticle SDK should access the kit's directly this is fine for some use cases, however in some situation we can't connect to the kit's system as we need to provide the setup during the kit's activation process, such as in this case.

**Comment by samdozor** [comment]
@ArkadiGiniApps sorry if I haven't been clear. We have an API, exactly for this, such that you don't need the configuration object. It's called the deeplinking or attribution API. You edited code right below it. Here's an example of what you could have changed to add support: https://github.com/mparticle-integrations/mparticle-android-integration-adjust/commit/4e19559c2aca5921add4773e154ac58bf1164b95

Then your app implementation would look something like:

```
public class SampleApplication extends Application implements AttributionListener {

    @Override
    public void onCreate() {
        super.onCreate();
        MParticleOptions options = MParticleOptions.builder(this)
                .credentials("FOO", "BAR")
                .attributionListener(this)
                .logLevel(MParticle.LogLevel.VERBOSE)
                .build();
        MParticle.start(options);
    }

    @Override
    public void onResult(AttributionResult attributionResult) {
       String adjustDeepLink = attributionResult.getLink();
       //handle the adjust deep link
    }

    @Override
    public void onError(AttributionError attributionError) {
        //no op
    }
}
```


The advantage of this is that you don't have to have a direct reference to Adjust's classes. Does that make sense? If you'd still like to move forward with the direct reference - then I'm good to accept this PR and release it but just wanted to make sure you understood this other option.

**Comment by ArkadiGiniApps** [comment]
@samdozor I fully comprehand the attribution listener option. however this is an INFORMATION only callback. It DOES NOT allow my to trigger a UI change via Adjust's system.

Something that I need to fully control as the SDK integrator.

This is also the reason why the changes you proposed in [4e19559](https://github.com/mparticle-integrations/mparticle-android-integration-adjust/commit/4e19559c2aca5921add4773e154ac58bf1164b95) are not suitable for my needs.

I need to be able to affect the value returned into Adjust.

**Comment by samdozor** [comment]
@ArkadiGiniApps got it - I see now that you are specifically referring to the ability to return true/false from `launchReceivedDeeplink`.  I had missed your reference to a boolean above. This is likely something we could add to our attribution listener to cover this case in the future.

Thanks for the additional commit - I'll have the team test it and merge it if all looks good!

**Comment by willpassidomo** [comment]
@ArkadiGiniApps Looks good to me, I;m going to merge this as is, since I've let this sit for too long as it is. 

One change I'd like to make later is to remove the new `OnDeeplinkEventListener`, it seems like it is a duplicate of `OnDeeplinkResponseListener` but with a different name, is there a reason we need the new class instead of making `deeplinkResponseListenerProxy` an object of type `OnDeeplinkResponseListener`?

**Pull request merged**
